# Generated by Django 6.0.3 on 2026-04-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_customuser_options_customuser_age_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="auth_provider",
            field=models.CharField(default="email", max_length=50),
        ),
        migrations.AddField(
            model_name="customuser",
            name="profile_picture",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
