# Generated by Django 5.2.8 on 2026-03-09 08:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("candidates", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ResumeReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("resume_file_name", models.TextField()),
                ("resume_file_url", models.TextField(blank=True, null=True)),
                ("overall_score", models.IntegerField()),
                ("ats_score", models.IntegerField()),
                ("strengths", models.JSONField()),
                ("weaknesses", models.JSONField()),
                ("analytics", models.JSONField()),
                ("recommendations", models.JSONField()),
                ("improved_bullet_example", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resume_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="candidates__user_id_8abacd_idx",
                    ),
                    models.Index(
                        fields=["ats_score"], name="candidates__ats_sco_04e48c_idx"
                    ),
                ],
            },
        ),
    ]
