# Generated by Django 6.0.3 on 2026-03-04 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interview", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InterviewSignup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interview_type",
                    models.CharField(
                        choices=[
                            ("technical", "Technical Interview"),
                            ("behavioral", "Behavioral Interview"),
                            ("both", "Both Technical and Behavioral"),
                        ],
                        default="technical",
                        max_length=20,
                    ),
                ),
                ("job_role", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "experience_level",
                    models.CharField(
                        choices=[
                            ("fresher", "Fresher"),
                            ("junior", "Junior (1-3 years)"),
                            ("mid", "Mid-Level (3-5 years)"),
                            ("senior", "Senior (5+ years)"),
                        ],
                        default="fresher",
                        max_length=20,
                    ),
                ),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "hiring_for_position",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("preferred_interview_date", models.DateField(blank=True, null=True)),
                ("interview_duration_minutes", models.IntegerField(default=30)),
                ("resume_uploaded", models.BooleanField(default=False)),
                ("resume_url", models.URLField(blank=True, null=True)),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "interview_completion_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("interview_score", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interview_signup",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="interview_i_user_id_5182ca_idx",
                    ),
                    models.Index(
                        fields=["is_completed"], name="interview_i_is_comp_dee181_idx"
                    ),
                ],
            },
        ),
    ]
