# Generated by Django 5.2.8 on 2026-03-09 08:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interview", "0002_interviewsignup"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InterviewReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("overall_score", models.IntegerField()),
                ("duration", models.IntegerField()),
                ("question_count", models.IntegerField()),
                ("response_count", models.IntegerField()),
                ("tone_analysis", models.JSONField()),
                ("skill_scores", models.JSONField()),
                ("strengths", models.JSONField()),
                ("improvements", models.JSONField()),
                ("detailed_feedback", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interview_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="interview_i_user_id_9595a9_idx",
                    ),
                    models.Index(
                        fields=["overall_score"], name="interview_i_overall_f0674d_idx"
                    ),
                ],
            },
        ),
    ]
