# Generated by Django 6.0.3 on 2026-04-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interview", "0003_interviewreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewreport",
            name="interview_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="interviewreport",
            name="session_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
